CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    username VARCHAR (255) NOT NULL UNIQUE,
    email VARCHAR (255) NOT NULL UNIQUE,
    password VARCHAR (255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE habits (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    name TEXT NOT NULL,
    frequency_per_week INTEGER DEFAULT 0,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE checkins (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    habit_id INTEGER NOT NULL REFERENCES habits(id) ON DELETE CASCADE,
    date_completed DATE NOT NULL DEFAULT CURRENT_DATE,
    UNIQUE (habit_id, date_completed)
);